version: "3"

networks:
  default:
    external:
      name: cw_net

services:
  cw-php:
    container_name: cw-php
    build:
      context: ../php/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../../dock-roboto/flowbusiness_co:/usr/share/apache2/htdocs/flowbusiness_co:delegated
      - ../../cwbusiness.com/core:/usr/share/apache2/htdocs/cwbusiness:delegated
      - ./logs:/var/log/php:delegated
